name: sundials4py-deploy

env:
  TWINE_USERNAME: __token__
  TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}

on:
  # Allows this workflow to be called by other workflows
  workflow_call:
  # Allows manual triggering
  workflow_dispatch:
  # Trigger deployment of wheels upon release
  release:
    types:
      - published

# Cancel any in-progress workflow runs
concurrency:
  group: sundials4py-deploy-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  sundials4py-deploy-build-and-test:
    name: Build and test
    if: github.event_name == 'release' && github.event.action == 'published'
    uses: ./.github/workflows/sundials4py-build-and-test.yml

  sundials4py-deploy-to-pypi:
    name: Publish sundials4py to pypi if release
    needs: [sundials4py-deploy-build-and-test]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
    - uses: actions/checkout@v7
      with:
        submodules: true
    - uses: actions/setup-python@v6
    - name: Install twine
      run: python -m pip install --upgrade twine
    - uses: actions/download-artifact@v8
      with:
        path: dist
        pattern: dist-*
        merge-multiple: true

    - name: Publish sundials4py artifacts
      env:
        PYPI_TOKEN: ${{ secrets.pypi_password }}
      run: ./scripts/publish_sundials4py_wheels.sh --dist-dir dist --include-sdist

