name: Build and Test - Windows/MSVC (short)

on:
  # Allows this workflow to be called by other workflows
  workflow_call:
  # Allows manual triggering
  workflow_dispatch:

# Cancel any in-progress workflow runs
concurrency:
  group: windows-msvc-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  BUILD_TYPE: Release

jobs:
  build_and_test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v7

    - name: Configure CMake
      run: cmake -W error=dev -G "Visual Studio 18 2026" -A x64 -B ${{github.workspace}}/build -DSUNDIALS_BUILD_WITH_PROFILING=ON -DSUNDIALS_TEST_ENABLE_UNIT_TESTS=ON -DEXAMPLES_ENABLE_CXX=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --verbose

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure

    - name: Archive build files from failed build
      uses: actions/upload-artifact@v7
      if: failure()
      with:
        name: build_files_msvc_${{ env.BUILD_TYPE }}
        path: |
          ${{ github.workspace }}/build
          !${{ github.workspace }}/build/Testing/output

    - name: Archive output files from failed build
      uses: actions/upload-artifact@v7
      if: failure()
      with:
        name: output_files_msvc_${{ env.BUILD_TYPE }}
        path: |
          ${{ github.workspace }}/build/Testing/
